---
- name: Deploy Glance
  ansible.builtin.include_role:
    name: service_deploy
  vars:
    service_name: "Glance"
    service_dir_name: "{{ glance_dir_name }}"
    compose_url: "https://raw.githubusercontent.com/glanceapp/docker-compose-template/refs/heads/main/root/docker-compose.yml"
    service_files:
      - src: "config/"
        dest: "config"
