---
- name: Deploy Glance
  ansible.builtin.include_role:
    name: service_deploy
  vars:
    service_name: "Glance"
    service_dir_name: "{{ glance_dir_name }}"
    service_files:
      - src: "config/"
        dest: "config"
