---
- name: Set up Glance
  vars:
    glance_dir: "/mnt/data/glance"

  block:
    - name: Create Glance directory
      ansible.builtin.file:
        path: "{{ glance_dir }}"
        state: directory

    - name: Copy docker-compose.yml to Glance directory
      ansible.builtin.template:
        src: "../templates/docker-compose.yml.j2"
        dest: "{{ glance_dir }}/docker-compose.yml"

    - name: Copy .env to Glance directory
      ansible.builtin.template:
        src: "../templates/.env.j2"
        dest: "{{ glance_dir }}/.env"

    - name: Copy config files to Glance directory
      ansible.builtin.copy:
        src: "../files/config"
        dest: "{{ glance_dir }}"

    - name: Start Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ glance_dir }}"
