---
- name: Deploy Wealthfolio
  ansible.builtin.include_role:
    name: service_deploy
  vars:
    service_name: "Wealthfolio"
    service_dir_name: "{{ wealthfolio_dir_name }}"
    compose_url: "https://raw.githubusercontent.com/wealthfolio/wealthfolio/9a4da25fc4477be93f5d169b251cf5a6e99e3373/compose.yml"
    data_dirs:
      - "data"
