---
- name: Deploy Wealthfolio
  ansible.builtin.include_role:
    name: service_deploy
  vars:
    service_name: "Wealthfolio"
    service_dir_name: "{{ wealthfolio_dir_name }}"
    compose_url: "https://raw.githubusercontent.com/afadil/wealthfolio/bc614863ea5b65ed2cccfd4179d7a52fc0658f55/compose.yml"
