server:
  proxied: true
  assets-path: /app/assets

theme:
  disable-picker: true
  background-color: 240 21 15
  contrast-multiplier: 1.2
  primary-color: 217 92 83
  positive-color: 115 54 76
  negative-color: 347 70 65
  custom-css-file: /assets/user.css

auth:
  secret-key: ${GLANCE_SECRET}
  users:
    ${GLANCE_USER}:
      password-hash: ${GLANCE_PASSWORD_HASH}

branding:
  logo-text: Dashboard
  app-name: Dashboard
  hide-footer: true
pages:
  # It's not necessary to create a new file for each page and include it, you can simply
  # put its contents here, though multiple pages are easier to manage when separated
  - $include: home.yml
  - $include: server.yml
  - $include: os.yml
