- name: OS
  columns:
    - size: small
      widgets:
        - type: bookmarks
          hide-header: true
          groups:
            - title: Documentation
              links:
                - title: Chezmoi
                  url: https://www.chezmoi.io/user-guide
                  icon: https://raw.githubusercontent.com/twpayne/chezmoi/refs/heads/master/assets/images/logo_blue_144.svg
                - title: Fastfetch
                  url: https://github.com/fastfetch-cli/fastfetch/wiki
                  icon: https://avatars.githubusercontent.com/u/136235211
                - title: Hyprland
                  url: https://wiki.hyprland.org
                  icon: https://upload.wikimedia.org/wikipedia/commons/7/7e/Hyprland_logo.png
                - title: Neovim
                  url: https://neovim.io/doc/user
                  icon: https://raw.githubusercontent.com/neovim/neovim.github.io/refs/heads/master/logos/neovim-mark.svg
                - title: Nushell
                  url: https://nushell.sh/book
                  icon: https://raw.githubusercontent.com/nushell/nushell/refs/heads/main/assets/icons/nushell-original.png
                - title: Rofi
                  url: https://davatorium.github.io/rofi
                  icon: si:wayland
                - title: Spicetify Nix
                  url: https://gerg-l.github.io/spicetify-nix
                  icon: di:spotify
                - title: tmux
                  url: https://github.com/tmux/tmux/wiki
                  icon: https://raw.githubusercontent.com/tmux/tmux/refs/heads/master/logo/tmux-logomark.svg
                - title: Waybar
                  url: https://github.com/Alexays/Waybar/wiki
                  icon: si:wayland
            - title: Nix
              links:
                - title: Nixpkgs
                  url: https://search.nixos.org/packages
                  icon: di:nixos
                - title: NixOS Options
                  url: https://search.nixos.org/options
                  icon: di:nixos
                - title: NixOS Wiki
                  url: https://wiki.nixos.org
                  icon: di:nixos
                - title: NixOS WSL
                  url: https://nix-community.github.io/NixOS-WSL
                  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/windows-11.webp
                - title: Nix Darwin
                  url: https://nix-darwin.github.io/nix-darwin/manual
                  icon: si:apple
            - title: Nix Manuals
              links:
                - title: NixOS Manual
                  url: https://nixos.org/nixos/manual/unstable
                  icon: di:nixos
                - title: Nixpkgs Manual
                  url: https://nixos.org/manual/nixpkgs/unstable
                  icon: di:nixos
                - title: Home Manager
                  url: https://nix-community.github.io/home-manager/options.xhtml
                  icon: di:nixos
            - title: GitHub Repositories
              links:
                - title: Dotfiles
                  url: https://github.com/Nitestack/dotfiles
                  icon: si:github
        - type: rss
          feeds:
            - url: https://nixos.org/blog/announcements-rss.xml

    - size: full
      widgets:
        - type: group
          widgets:
            - type: reddit
              subreddit: unixporn
            - type: reddit
              subreddit: hyprland
            - type: reddit
              subreddit: NixOS
            - type: reddit
              subreddit: neovim

        - type: videos
          channels:
            - UCg6gPGh8HU2U01vaFCAsvmQ # Chris Titus Tech
            - UCEEVcDuBRDiwxfXAgQjLGug # Dreams of Autonomy
            - UCWQaM7SpSECp9FELz-cHzuQ # Dreams of Code
            - UCYeiozh-4QwuC1sjgCmB92w # DevOps Toolbox
            - UC0sUzmZ0CHvVCVrpRfGKZfw # My Linux For Work
            - UCVk4b-svNJoeytrrlOixebQ # TheVimeagen
            - UCo71RUe6DX4w-Vd47rFLXPg # typecraft
            - UC_zBdZ0_H_jn41FDRG7q4Tw # Vimjoyer

    - size: small
      widgets:
        - type: releases
          title: Desktop Environment
          token: ${GITHUB_API_TOKEN}
          show-source-icon: true
          collapse-after: -1
          repositories:
            - hyprwm/Hyprland
            - hyprwm/hyprcursor
            - hyprwm/hypridle
            - hyprwm/hyprlock
            - hyprwm/hyprpicker
            - hyprwm/hyprsunset
            - sddm/sddm
            - ErikReider/SwayNotificationCenter
            - LGFae/swww
            - Alexays/Waybar

        - type: releases
          title: Applications
          token: ${GITHUB_API_TOKEN}
          show-source-icon: true
          collapse-after: -1
          repositories:
            - bitwarden/clients
            - ONLYOFFICE/DesktopEditors
            - nextcloud/desktop
            - slgobinath/SafeEyes
            - signalapp/Signal-Desktop
            - microsoft/vscode
            - anufrievroman/waypaper
            - xeco23/WasIstLos
            - Vencord/Vesktop
            - zen-browser/desktop

        - type: releases
          title: CLI Tools
          token: ${GITHUB_API_TOKEN}
          show-source-icon: true
          collapse-after: -1
          repositories:
            - sharkdp/bat
            - aristocratos/btop
            - caddyserver/caddy
            - carapace-sh/carapace
            - karlstav/cava
            - twpayne/chezmoi
            - eza-community/eza
            - fastfetch-cli/fastfetch
            - sharkdp/fd
            - neovim/neovim
            - nushell/nushell
            - BurntSushi/ripgrep
            - spicetify/cli
            - tmux/tmux
