---
- name: Discover roles with backup tasks
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Find all backup.yml files in the roles directory
      ansible.builtin.find:
        paths: "{{ playbook_dir }}/roles"
        patterns: "backup.yml"
        recurse: true
      register: backup_files

    - name: Create a list of roles with backup tasks
      ansible.builtin.set_fact:
        backup_roles: "{{ backup_files.files | map(attribute='path') | map('dirname') | map('dirname') | map('basename') | list }}"

- name: Execute backups and clean up old files
  hosts: raspberrypi
  gather_facts: true
  vars:
    backup_retention_days: 7
  tasks:
    - name: Run backup tasks for each discovered role
      ansible.builtin.include_role:
        name: "{{ item }}"
        tasks_from: backup.yml
      loop: "{{ hostvars['localhost']['backup_roles'] }}"
      loop_control:
        label: "{{ item }}"
      when: services[item].enabled
