---
- name: Deploy Services
  hosts: raspberrypi
  gather_facts: true

  roles:
    - role: common
      tags: common
    - role: ufw
      tags: ufw
    - role: fail2ban
      tags: fail2ban
    - role: docker
      tags: docker
    - role: caddy
      tags: caddy
    - role: cloudflare_ddns
      tags: cloudflare_ddns

    - role: gitea
      tags: gitea
    - role: wg_easy
      tags: wg_easy
    - role: authentik
      tags: authentik
    - role: nextcloud
      tags: nextcloud
    - role: immich
      tags: immich
    - role: vaultwarden
      tags: vaultwarden
    - role: ente_auth
      tags: ente_auth
    - role: ghostfolio
      tags: ghostfolio
    - role: n8n
      tags: n8n
    - role: wger
      tags: wger
    - role: glance
      tags: glance
    - role: beszel
      tags: beszel
    - role: calibre_web
      tags: calibre_web
    - role: adguard_home
      tags: adguard_home
    - role: adventure_log
      tags: adventure_log
    - role: freshrss
      tags: freshrss

    - role: personal_site
      tags: personal_site

    - role: backrest
      tags: backup,backrest
    - role: backup
      tags: backup
