---
- name: Deploy Services
  hosts: raspberrypi
  gather_facts: true

  roles:
    - role: common
      tags: common
    - role: ufw
      tags: ufw
    - role: fail2ban
      tags: fail2ban
    - role: docker
      tags: docker
    - role: caddy
      tags: caddy
    - role: cloudflare_tunnel
      tags: cloudflare_tunnel

    - role: pocket_id
      tags: pocket_id
    - role: nextcloud
      tags: nextcloud
    - role: immich
      tags: immich
    - role: vaultwarden
      tags: vaultwarden
    - role: ente_auth
      tags: ente_auth
    - role: ghostfolio
      tags: ghostfolio
    - role: navidrome
      tags: navidrome
    - role: beets
      tags: beets
    - role: prowlarr
      tags: prowlarr
    - role: rdtclient
      tags: rdtclient
    - role: wger
      tags: wger
    - role: glance
      tags: glance
    - role: beszel
      tags: beszel
    - role: yamtrack
      tags: yamtrack
    - role: calibre_web_automated
      tags: calibre_web_automated
    - role: adguard_home
      tags: adguard_home
    - role: adventure_log
      tags: adventure_log
    - role: freshrss
      tags: freshrss

    - role: zerobyte
      tags: backup,zerobyte
    - role: backup
      tags: backup
