---
- name: Raspberry Pi 5
  hosts: raspberrypi
  become: true
  gather_facts: true

  roles:
    - role: common
      tags: common
    - role: ufw
      tags: ufw
    - role: fail2ban
      tags: fail2ban
    - role: docker
      tags: docker
    - role: caddy
      tags: caddy
    - role: cloudflare_ddns
      tags: cloudflare_ddns
    - role: wg_easy
      tags: wg_easy

    - role: nextcloud
      tags: nextcloud
    - role: immich
      tags: immich
    - role: vaultwarden
      tags: vaultwarden
    - role: ente_auth
      tags: ente_auth
    - role: ghostfolio
      tags: ghostfolio
    - role: glance
      tags: glance
    - role: adguard_home
      tags: adguard_home
    - role: adventure_log
      tags: adventure_log
    - role: freshrss
      tags: freshrss

    - role: personal_site
      tags: personal_site

    - role: stefangweichinger.ansible_rclone
      tags: backup, rclone
    - role: angristan.restic
      tags: backup, restic
      vars:
        restic_ssh_enabled: false
        # restic_repository: "rclone:proton-drive:backup"
        restic_repository: "rclone:onedrive:backup"
        restic_default_folders: []
        restic_folders:
          - { path: "/mnt/data", exclude: "--exclude '/mnt/data/nextcloud'" }
        restic_systemd_timer_on_calender: "*-*-* 03:00:00"
        restic_forget_keep_within: "30d"
