---
- name: Raspberry Pi 5
  hosts: raspberrypi
  become: true
  gather_facts: true

  vars_files:
    - secrets.yml

  roles:
    - common
    - ufw
    - fail2ban
    - docker
    - caddy
    - cloudflare-ddns-updater
    - wg-easy
    - dotfiles

    - nextcloud
    - immich
    - vaultwarden
    - ente-auth
    - ghostfolio
    - glance
    - adguard-home
    - adventure-log
    - freshrss

    - personal-site
