---
- name: Raspberry Pi 5
  hosts: raspberrypi
  become: true
  gather_facts: true

  roles:
    - common
    - ufw
    - fail2ban
    - docker
    - caddy
    - cloudflare_ddns
    - wg_easy

    - nextcloud
    - immich
    - vaultwarden
    - ente_auth
    - ghostfolio
    - glance
    - adguard_home
    - adventure_log
    - freshrss

    - personal_site
