---
- name: Raspberry Pi 5
  hosts: raspberrypi
  become: true
  gather_facts: true

  vars_files:
    - secrets.yml

  pre_tasks:
    - name: Upgrade system
      ansible.builtin.import_tasks: pre_tasks/upgrade_system.yml
    - name: Static IPv4
      ansible.builtin.import_tasks: pre_tasks/ipv4.yml
    - name: Gather package facts
      ansible.builtin.import_tasks: pre_tasks/gather_facts.yml
    - name: Ensure the keyrings directory exists
      ansible.builtin.import_tasks: pre_tasks/keyrings_dir.yml
    - name: Ensure the NVME SSDs are mounted
      ansible.builtin.import_tasks: pre_tasks/mount_nvme_ssds.yml
    - name: Suppress login message
      ansible.builtin.import_tasks: pre_tasks/suppress_login_message.yml
  post_tasks:
    - name: Display new public key for manual GitHub setup
      ansible.builtin.debug:
        msg: "Copy this public key into your GitHub account: {{ keypair_result.public_key }}"
      when: keypair_result.changed

  roles:
    - dotfiles
    - docker
    - caddy
    - cloudflare-ddns-updater

    - nextcloud
    - immich
    - vaultwarden
    - glance
    - ente-auth
    - ghostfolio
    - adguard-home
    - freshrss
    - pivpn
    - personal-site
    - adventure-log
