---
- name: Raspberry Pi 5
  hosts: raspberrypi
  become: true
  gather_facts: true

  vars_files:
    - secrets.yml

  pre_tasks:
    - name: Upgrade system
      ansible.builtin.import_tasks: pre_tasks/upgrade_system.yml
    - name: Static IPv4
      ansible.builtin.import_tasks: pre_tasks/ipv4.yml
    - name: Gather package facts
      ansible.builtin.import_tasks: pre_tasks/gather_facts.yml
    - name: Ensure the keyrings directory exists
      ansible.builtin.import_tasks: pre_tasks/keyrings_dir.yml
    - name: Ensure the NVME SSDs are mounted
      ansible.builtin.import_tasks: pre_tasks/mount_nvme_ssds.yml
    - name: Suppress login message
      ansible.builtin.import_tasks: pre_tasks/suppress_login_message.yml

  roles:
    - zsh
    - docker
    - vaultwarden
    - cloudflare-ddns-updater
    - pivpn
    - nextcloud
