---
- name: wger Backup
  ansible.builtin.include_role:
    name: service_backup
  vars:
    service_name: "wger"
    service_dir_name: "{{ wger_dir_name }}"
    run_service_name: "db"
    run_command_env:
      PGHOST: "db"
      PGDATABASE: "wger"
      PGUSER: "wger"
      PGPASSWORD: "{{ wger_db_password }}"
    stop_services:
      - "web"
      - "cache"
      - "celery_worker"
      - "celery_beat"
  tags:
    - skip_ansible_lint
