---
- name: Deploy wger
  ansible.builtin.include_role:
    name: service_deploy
  vars:
    service_name: "wger"
    service_dir_name: "{{ wger_dir_name }}"
    compose_url: "https://raw.githubusercontent.com/wger-project/docker/b1cf3561f779b234f590bebb0a58494ae134bd97/docker-compose.yml"
    env_url: "https://raw.githubusercontent.com/wger-project/docker/800fe02e75fadf62f6cba5fd810f6c496f98ea3f/config/prod.env"
    service_downloads:
      - url: "https://raw.githubusercontent.com/wger-project/docker/refs/heads/master/config/redis.conf"
        dest: "redis.conf"
    data_dirs:
      - "static"
      - "media"
      - "db"
      - "redis"
      - "beat"
