---
- name: Deploy wger
  ansible.builtin.include_role:
    name: service_deploy
  vars:
    service_name: "wger"
    service_dir_name: "{{ wger_dir_name }}"
    compose_url: "https://raw.githubusercontent.com/wger-project/docker/b1cf3561f779b234f590bebb0a58494ae134bd97/docker-compose.yml"
    env_url: "https://raw.githubusercontent.com/wger-project/docker/5d75d0c473cc2610e3d89bd70e8bdf3befc41d72/config/prod.env"
    service_downloads:
      - url: "https://raw.githubusercontent.com/wger-project/docker/refs/heads/master/config/redis.conf"
        dest: "redis.conf"
    data_dirs:
      - "static"
      - "media"
      - "db"
      - "redis"
      - "beat"
