---
# The display name for the service
service_name: "{{ service_dir_name | replace('-', ' ') | title }}"

# The directory name for the service
service_dir_name: ""

# The service name from the docker compose file to run the command against
run_service_name: ""

# The command to execute for the database dump
run_command: "pg_dumpall -c"

# Environment variables
run_command_env: {}

# Set to false for commands that create files instead of printing
run_command_produces_stdout: true

# List of specific directory paths to back up
data_paths: []

# List of services to stop before backup
stop_services: []
