---
- name: Deploy Caddy
  ansible.builtin.include_role:
    name: service_deploy
  vars:
    service_name: "Caddy"
    service_dir_name: "{{ caddy_dir_name }}"
    service_templates:
      - src: "Caddyfile.j2"
        dest: "Caddyfile"
    service_files:
      - src: "static/"
        dest: "static"
      - src: "update_public_ip.sh"
        dest: "update_public_ip.sh"

- name: Create cron job for public IP updating
  ansible.builtin.cron:
    name: "Caddy Public IP Updater"
    minute: "*/1"
    job: "{{ caddy_service_dir }}/update_public_ip.sh"
