---
- name: Install Caddy
  when: "'caddy' not in ansible_facts.packages"
  vars:
    gpg_key_tmp_file: /tmp/caddy.gpg.key
    gpg_key_file: /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  block:
    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - debian-keyring
          - debian-archive-keyring
          - apt-transport-https
        update_cache: true

    - name: Download GPG key
      ansible.builtin.get_url:
        url: "https://dl.cloudsmith.io/public/caddy/stable/gpg.key"
        dest: "{{ gpg_key_tmp_file }}"
        mode: "0644"

    - name: Convert GPG key to keyring format
      ansible.builtin.command:
        cmd: "gpg --dearmor -o {{ gpg_key_file }} {{ gpg_key_tmp_file }}"
      args:
        creates: "{{ gpg_key_file }}"

    - name: Remove temporary GPG key
      ansible.builtin.file:
        name: "{{ gpg_key_tmp_file }}"
        state: absent

    - name: Download repository list
      ansible.builtin.get_url:
        url: "https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt"
        dest: /etc/apt/sources.list.d/caddy-stable.list
        mode: "0644"

    - name: Install
      ansible.builtin.apt:
        name: caddy
        update_cache: true
