---
- name: Deploy Caddy
  ansible.builtin.include_role:
    name: service_deploy
  vars:
    service_name: "Caddy"
    service_dir_name: "{{ caddy_dir_name }}"
    service_templates:
      - src: "Caddyfile.j2"
        dest: "Caddyfile"
    service_files:
      - src: "static/"
        dest: "static"
