- name: Install bat
  block:
    - name: Install
      ansible.builtin.apt:
        name: bat
        update_cache: true
      when: "'bat' not in ansible_facts.packages"

    - name: Ensure .local/bin directory exists
      file:
        path: "/home/{{ ansible_user }}/.local/bin"
        state: directory
      become_user: "{{ ansible_user }}"

    - name: Ensure symlink to bat bin is set up
      ansible.builtin.file:
        src: /usr/bin/batcat
        dest: "/home/{{ ansible_user }}/.local/bin/bat"
        state: link
