- name: Install delta
  block:
    - name: Check if already installed
      ansible.builtin.command: dpkg-query -W git-delta
      register: delta_res
      failed_when: delta_res.rc > 1
      changed_when: delta_res.rc == 1

    - name: Check latest delta version
      ansible.builtin.uri:
        url: "https://api.github.com/repos/dandavison/delta/releases/latest"
        return_content: true
        body_format: json
      register: response
      when: delta_res.rc == 1

    - name: Install
      ansible.builtin.apt:
        deb: "https://github.com/dandavison/delta/releases/latest/download/git-delta_{{ response.json.tag_name }}_arm64.deb"
      when: delta_res.rc == 1
