- name: Install fastfetch
  block:
    - name: Check if already installed
      ansible.builtin.command: dpkg-query -W fastfetch
      register: fastfetch_res
      failed_when: fastfetch_res.rc > 1
      changed_when: fastfetch_res.rc == 1

    - name: Install dependencies
      ansible.builtin.apt:
        name: xz-utils
        update_cache: true

    - name: Install
      ansible.builtin.apt:
        deb: "https://github.com/fastfetch-cli/fastfetch/releases/latest/download/fastfetch-linux-aarch64.deb"
      when: fastfetch_res.rc == 1
