---
- name: Set up Dotfiles
  vars:
    ssh_key_type: ed25519
  block:
    - name: Install Git
      ansible.builtin.apt:
        name: git
        update_cache: true
      when: "'git' not in ansible_facts.packages"
    - name: Install Nushell
      ansible.builtin.include_tasks: ./nushell.yml
    - name: Install chezmoi
      ansible.builtin.include_tasks: ./chezmoi.yml
    - name: Install bat
      ansible.builtin.include_tasks: ./bat.yml
    - name: Install carapace
      ansible.builtin.include_tasks: ./carapace.yml
    - name: Install delta
      ansible.builtin.include_tasks: ./delta.yml
    - name: Install eza
      ansible.builtin.include_tasks: ./eza.yml
    - name: Install fastfetch
      ansible.builtin.include_tasks: ./fastfetch.yml
    - name: Install lazygit
      ansible.builtin.include_tasks: ./lazygit.yml
    - name: Install Oh My Posh
      ansible.builtin.include_tasks: ./oh-my-posh.yml
    - name: Install vivid
      ansible.builtin.include_tasks: ./vivid.yml
    - name: Install zoxide
      ansible.builtin.include_tasks: ./zoxide.yml

    - name: Add GitHub to ~/.ssh/known_hosts
      ansible.builtin.known_hosts:
        name: "github.com"
        key: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
      become_user: "{{ ansible_user }}"

    - name: Generate SSH keypair for user (if absent)
      community.crypto.openssh_keypair:
        path: "/home/{{ ansible_user }}/.ssh/id_{{ ssh_key_type }}"
        type: "{{ ssh_key_type }}"
      become_user: "{{ ansible_user }}"
      register: keypair_result

    - name: Check if Dotfiles exists
      ansible.builtin.stat:
        path: "/home/{{ ansible_user }}/.dotfiles"
      register: dotfiles_stat

    - name: Download Dotfiles
      ansible.builtin.git:
        dest: "/home/{{ ansible_user }}/.dotfiles"
        repo: "git@github.com:Nitestack/dotfiles.git"
        accept_hostkey: true
        key_file: "/home/{{ ansible_user }}/.ssh/id_{{ ssh_key_type }}"
      when: not dotfiles_stat.stat.exists
      become_user: "{{ ansible_user }}"
