- name: Install Oh My Posh
  block:
    - name: Ensure .local/bin directory exists
      file:
        path: "/home/{{ ansible_user }}/.local/bin"
        state: directory
      become_user: "{{ ansible_user }}"

    - name: Install
      ansible.builtin.shell: curl -s https://ohmyposh.dev/install.sh | bash -s -- -d ~/.local/bin
      args:
        creates: "/home/{{ ansible_user }}/.local/bin/oh-my-posh"
      become_user: "{{ ansible_user }}"
