- name: Install vivid
  block:
    - name: Check if already installed
      ansible.builtin.command: dpkg-query -W vivid
      register: vivid_res
      failed_when: vivid_res.rc > 1
      changed_when: vivid_res.rc == 1

    - name: Check latest vivid version
      ansible.builtin.uri:
        url: "https://api.github.com/repos/sharkdp/vivid/releases/latest"
        return_content: true
        body_format: json
      register: response
      when: vivid_res.rc == 1

    - name: Install
      ansible.builtin.apt:
        deb: "https://github.com/sharkdp/vivid/releases/latest/download/vivid_{{ response.json.tag_name | regex_replace('^v(?=[0-9])', '') }}_arm64.deb"
      when: vivid_res.rc == 1
