# external-file: https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
# digest: 22864ad0dcc4aefcfde39d804a20ea0e065841450dfb7902edc7963b61ff3dfe

---
- name: Deploy Immich
  ansible.builtin.include_role:
    name: service_deploy
  vars:
    service_name: "Immich"
    service_dir_name: "{{ immich_dir_name }}"
    compose_url: "https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml"
