---
- name: Ensure Immich data directory exists
  ansible.builtin.file:
    path: "{{ immich_dir }}"
    state: directory
    mode: "0755"

- name: Download the latest docker-compose.yml for Immich
  ansible.builtin.get_url:
    url: "https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml"
    dest: "{{ immich_dir }}/compose.yml"
    mode: "0644"

- name: Deploy .env file from template
  ansible.builtin.template:
    src: ".env.j2"
    dest: "{{ immich_dir }}/.env"
    mode: "0644"

- name: Ensure Immich containers are started
  community.docker.docker_compose_v2:
    project_src: "{{ immich_dir }}"
    state: present
