---
- name: Deploy Immich
  ansible.builtin.include_role:
    name: service_deploy
  vars:
    service_name: "Immich"
    service_dir_name: "{{ immich_dir_name }}"
    compose_url: "https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml"
