---
- name: Set up Immich
  vars:
    immich_dir: "/mnt/data/immich"

  block:
    - name: Create Immich directory
      ansible.builtin.file:
        path: "{{ immich_dir }}"
        state: directory

    - name: Download docker-compose.yml
      ansible.builtin.get_url:
        url: "https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml"
        dest: "{{ immich_dir }}/docker-compose.yml"

    - name: Ensure Immich Server has Glance labels
      ansible.builtin.blockinfile:
        path: "{{ immich_dir }}/docker-compose.yml"
        insertafter: '^\s+immich-server:'
        marker_begin: immich-server-begin
        marker_end: immich-server-end
        append_newline: true
        block: |
          #   Glance Label
              labels:
                glance.id: immich
                glance.name: Immich
                glance.icon: di:immich
                glance.url: "{{ IMMICH_URL }}"
                glance.hide: false

    - name: Ensure Immich Machine Learning has Glance labels
      ansible.builtin.blockinfile:
        path: "{{ immich_dir }}/docker-compose.yml"
        insertafter: '^\s+immich-machine-learning:'
        marker_begin: immich-machine-learning-begin
        marker_end: immich-machine-learning-end
        append_newline: true
        block: |
          #   Glance Label
              labels:
                glance.parent: immich
                glance.name: Machine Learning
                glance.hide: false

    - name: Ensure Redis has Glance labels
      ansible.builtin.blockinfile:
        path: "{{ immich_dir }}/docker-compose.yml"
        insertafter: '^\s+redis:'
        marker_begin: immich-redis-begin
        marker_end: immich-redis-end
        append_newline: true
        block: |
          #   Glance Label
              labels:
                glance.parent: immich
                glance.name: Redis
                glance.hide: false

    - name: Ensure DB has Glance labels
      ansible.builtin.blockinfile:
        path: "{{ immich_dir }}/docker-compose.yml"
        insertafter: '^\s+database:'
        marker_begin: immich-db-begin
        marker_end: immich-db-end
        append_newline: true
        block: |
          #   Glance Label
              labels:
                glance.parent: immich
                glance.name: DB
                glance.hide: false

    - name: Copy .env to Immich directory
      ansible.builtin.template:
        src: "../files/.env.j2"
        dest: "{{ immich_dir }}/.env"

    - name: Start Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ immich_dir }}"
