---
- name: Ensure Ente Auth data directory exists
  ansible.builtin.file:
    path: "{{ ente_auth_dir }}"
    state: directory
    mode: "0755"

- name: Deploy Docker Compose file from template
  ansible.builtin.template:
    src: "compose.yml.j2"
    dest: "{{ ente_auth_dir }}/compose.yml"
    mode: "0644"

- name: Deploy museum.yml file from template
  ansible.builtin.template:
    src: "museum.yml.j2"
    dest: "{{ ente_auth_dir }}/museum.yml"
    mode: "0644"

- name: Ensure Ente containers are started
  community.docker.docker_compose_v2:
    project_src: "{{ ente_auth_dir }}"
    state: present
