name: External File Updates

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  monitor:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - id: check-changes
        run: .gitea/scripts/check_external_files.sh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - if: steps.check-changes.outputs.changes == 'true'
        run: .gitea/scripts/update_commit_hashes.sh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - if: steps.check-changes.outputs.changes == 'true'
        run: |
          JSON_PAYLOAD=$(cat <<EOF
          {
            "base": "main",
            "head": "external-file-updates",
            "title": "chore(deps): update external file commit hashes",
            "body": "This PR contains the following updates:\n\n${{ env.CHANGES_REPORT }}\n\n---\n\n### ✅ What This PR Does:\n- **Automatically updates** all commit hash comments to match the latest commit of the external files.\n- **Ready to merge** after you review the external changes.\n\n### 📋 Action Required:\n1. **Review the diffs** to understand what changed.\n2. **Update your Ansible templates** if the external file structure changed significantly.\n3. **Merge this PR** once you're satisfied with the changes.",
            "reviewers": [
              "Nitestack"
            ]
          }
          EOF
          )

          curl --fail -X POST \
            -H "Authorization: token ${{ secrets.GT_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "${JSON_PAYLOAD}" \
            "${{ gitea.server_url }}/api/v1/repos/${{ gitea.repository }}/pulls"
