---
# The display name for the service
service_name: "{{ service_dir_name | replace('-', ' ') | title }}"

# The directory name for the service
service_dir_name: ""

# Directories to create for the service
data_dirs: []

# Additional downloads
service_downloads: []

# List of additional templates to copy
service_templates: []

# Optional Docker compose URL
compose_url: ""
# Optional .env URL
env_url: ""

# List of additional files/directories to copy
service_files: []
