---
- name: Install and configure rclone
  become: true
  block:
    - name: Include rclone role
      ansible.builtin.include_role:
        name: stefangweichinger.ansible_rclone

- name: Include Backrest role
  ansible.builtin.include_role:
    name: backrest
