---
- name: Deploy n8n
  ansible.builtin.include_role:
    name: service_deploy
  vars:
    service_name: "n8n"
    service_dir_name: "{{ n8n_dir_name }}"
    compose_url: "https://raw.githubusercontent.com/n8n-io/n8n-hosting/refs/heads/main/docker-caddy/docker-compose.yml"
  tags:
    - skip_ansible_lint
