---
- name: Set up PiVPN
  vars:
    install_script_path: "/tmp/install_pivpn.sh"
    options_conf_path: "/home/{{ ansible_user }}/pivpn_options.conf"
  block:
    - name: Create options.conf for unattended installation
      ansible.builtin.copy:
        dest: "{{ options_conf_path }}"
        content: |
          IPv4dev=eth0
          IPv6dev=eth0
          install_user={{ ansible_user }}
          VPN=wireguard
          pivpnDNS1=1.1.1.1 # Cloudflare
          pivpnDNS2=1.0.0.1 # Cloudflare
          pivpnHOST={{ PIVPN_URL }}
          pivpnPORT={{ PIVPN_PORT }}
        mode: "0644"
      register: options_conf
    - name: Run PiVPN installer if options.conf changed
      when: options_conf.changed
      block:
        - name: Download installer script
          ansible.builtin.get_url:
            url: https://install.pivpn.io
            dest: "{{ install_script_path }}"
            mode: "0755"

        - name: Run PiVPN installer script in unattended mode
          ansible.builtin.command:
            cmd: "bash {{ install_script_path }} --unattended {{ options_conf_path }}"
          become_user: "{{ ansible_user }}"

        - name: Clean up PiVPN installer script
          ansible.builtin.file:
            path: "{{ install_script_path }}"
            state: absent
