- name: Install eza
  when: "'eza' not in ansible_facts.packages"
  vars:
    gpg_key_tmp_file: /tmp/eza.gpg.key
    gpg_key_file: /etc/apt/keyrings/gierens.gpg
  block:
    - name: Install dependencies
      ansible.builtin.apt:
        name: gpg
        update_cache: true

    - name: Download GPG key
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/eza-community/eza/main/deb.asc"
        dest: "{{ gpg_key_tmp_file }}"
        mode: "0644"

    - name: Convert GPG key to keyring format
      ansible.builtin.command:
        cmd: "gpg --dearmor -o {{ gpg_key_file }} {{ gpg_key_tmp_file }}"
      args:
        creates: "{{ gpg_key_file }}"

    - name: Remove temporary GPG key
      ansible.builtin.file:
        name: "{{ gpg_key_tmp_file }}"
        state: absent

    - name: Add eza repository to sources list
      ansible.builtin.apt_repository:
        repo: "deb [arch=arm64 signed-by={{ gpg_key_file }}] http://deb.gierens.de stable main"
        filename: gierens

    - name: Install
      ansible.builtin.apt:
        name: eza
        update_cache: true
