- name: Install Oh My Posh
  vars:
    ohmyposh_config_dir: "/home/{{ ansible_user }}/.config/oh-my-posh"
  block:
    - name: Ensure .local/bin directory exists
      file:
        path: "/home/{{ ansible_user }}/.local/bin"
        state: directory
      become_user: "{{ ansible_user }}"

    - name: Install
      ansible.builtin.shell: curl -s https://ohmyposh.dev/install.sh | bash -s -- -d ~/.local/bin
      args:
        creates: "/home/{{ ansible_user }}/.local/bin/oh-my-posh"
      become_user: "{{ ansible_user }}"

    - name: Ensure Oh My Posh config directory exists
      ansible.builtin.file:
        path: "{{ ohmyposh_config_dir }}"
        state: directory

    - name: Copy config
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/Nitestack/dotfiles/refs/heads/master/config/private_dot_config/exact_oh-my-posh/config.yml"
        dest: "{{ ohmyposh_config_dir }}/config.yml"
