---
- name: Set up Beaver Habits Tracker
  vars:
    beaverhabits_dir: "/mnt/data/beaverhabits"

  block:
    - name: Create Beaver Habits Tracker directory
      ansible.builtin.file:
        path: "{{ beaverhabits_dir }}"
        state: directory

    - name: Copy docker-compose.yml to Beaver Habits Tracker directory
      ansible.builtin.template:
        src: "../files/docker-compose.yml.j2"
        dest: "{{ beaverhabits_dir }}/docker-compose.yml"

    - name: Start Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ beaverhabits_dir }}"
