---
- name: Set up FreshRSS
  vars:
    freshrss_dir: "/mnt/data/freshrss"

  block:
    - name: Create FreshRSS directory
      ansible.builtin.file:
        path: "{{ freshrss_dir }}"
        state: directory

    - name: Copy docker-compose.yml to FreshRSS directory
      ansible.builtin.template:
        src: "../templates/docker-compose.yml.j2"
        dest: "{{ freshrss_dir }}/docker-compose.yml"

    - name: Start Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ freshrss_dir }}"
