---
- name: Deploy FreshRSS
  ansible.builtin.include_role:
    name: service_deploy
  vars:
    service_name: "FreshRSS"
    service_dir_name: "{{ freshrss_dir_name }}"
    compose_url: "https://raw.githubusercontent.com/FreshRSS/FreshRSS/dcec27c69d9800ece797b710d9b61104d3aca57d/Docker/freshrss/docker-compose.yml"
