---
- name: Vaultwarden Backup
  ansible.builtin.include_role:
    name: service_backup
  vars:
    service_name: "Vaultwarden"
    service_dir_name: "{{ vaultwarden_dir_name }}"
    run_service_name: "vaultwarden"
    run_command: "/vaultwarden backup"
    run_command_produces_stdout: false
    data_paths:
      - "data/"
