---
- name: Set up AdGuard Home
  vars:
    adguard_dir: "/mnt/data/adguard-home"

  block:
    - name: Create AdGuard Home directory
      ansible.builtin.file:
        path: "{{ adguard_dir }}"
        state: directory

    - name: Copy docker-compose.yml to AdGuard Home directory
      ansible.builtin.template:
        src: "../files/docker-compose.yml.j2"
        dest: "{{ adguard_dir }}/docker-compose.yml"

    - name: Start Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ adguard_dir }}"
