---
- name: Install and configure Fail2Ban
  become: true
  block:
    - name: Install Fail2ban
      ansible.builtin.apt:
        name: fail2ban
        state: present
        update_cache: true

    - name: Deploy Fail2ban local jail configuration
      ansible.builtin.template:
        src: "jail.local.j2"
        dest: "/etc/fail2ban/jail.local"
        mode: "0644"
      notify: Restart fail2ban

    - name: Start and enable Fail2Ban service
      ansible.builtin.service:
        name: fail2ban
        state: started
        enabled: true
