---
- name: Perform system-level configuration
  become: true
  block:
    - name: Update and upgrade system packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist

    - name: Configure network for DHCP
      community.general.nmcli:
        type: ethernet
        conn_name: "Wired connection 1"
        method4: auto
        state: present
        conn_reload: true

    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: apt

    - name: Create APT keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Create mount point directories for NVMe devices
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        mode: "0755"
      loop: "{{ common_nvme_mounts }}"
      loop_control:
        label: "{{ item.path }}"

    - name: Format NVMe devices
      community.general.filesystem:
        fstype: "{{ item.filesystem }}"
        dev: "{{ item.device }}"
      loop: "{{ common_nvme_mounts }}"
      loop_control:
        label: "{{ item.device }}"

    - name: Mount NVMe devices
      ansible.posix.mount:
        path: "{{ item.path }}"
        src: "{{ item.device }}"
        fstype: "{{ item.filesystem }}"
        opts: "defaults"
        state: mounted
      loop: "{{ common_nvme_mounts }}"
      loop_control:
        label: "{{ item.path }}"

- name: Suppress login message
  ansible.builtin.file:
    path: "~/.hushlogin"
    state: file
    mode: "0644"

- name: Create base directory for all services
  ansible.builtin.file:
    path: "{{ service_base_dir }}"
    state: directory
    mode: "0755"
