---
- name: Ensure the data mount point exists
  ansible.builtin.file:
    path: /mnt/data
    state: directory

- name: Ensure the backup mount point exists
  ansible.builtin.file:
    path: /mnt/backup
    state: directory

- name: Check if data NVMe SSD is formatted
  ansible.builtin.command: lsblk -no FSTYPE /dev/nvme0n1
  register: data_nvme_fs
  changed_when: false

- name: Check if backup NVMe SSD is formatted
  ansible.builtin.command: lsblk -no FSTYPE /dev/nvme1n1
  register: backup_nvme_fs
  changed_when: false

- name: Format the data NVMe SSD if not formatted
  community.general.filesystem:
    fstype: ext4
    dev: /dev/nvme0n1
  when: data_nvme_fs.stdout == ""

- name: Format the backup NVMe SSD if not formatted
  community.general.filesystem:
    fstype: ext4
    dev: /dev/nvme1n1
  when: backup_nvme_fs.stdout == ""

- name: Mount the data NVMe SSD
  ansible.posix.mount:
    path: /mnt/data
    src: /dev/nvme0n1
    fstype: ext4
    opts: defaults
    state: mounted

- name: Mount the backup NVMe SSD
  ansible.posix.mount:
    path: /mnt/backup
    src: /dev/nvme1n1
    fstype: ext4
    opts: defaults
    state: mounted
