---
- name: Install Docker and configure user
  become: true
  block:
    - name: Perform Docker installation
      when: "'docker-ce' not in ansible_facts.packages"
      block:
        - name: Ensure conflicting packages are removed
          ansible.builtin.apt:
            name: "{{ docker_conflicting_packages }}"
            state: absent
            purge: true

        - name: Ensure dependencies are installed
          ansible.builtin.apt:
            name: "{{ docker_dependencies }}"
            state: present
            update_cache: true

        - name: Ensure GPG keyring directory exists
          ansible.builtin.file:
            path: "{{ docker_gpg_keyring_path }}"
            state: directory
            mode: "0755"

        - name: Ensure Docker GPG key is downloaded
          ansible.builtin.get_url:
            url: "{{ docker_gpg_key_url }}"
            dest: "{{ docker_gpg_key_path }}"
            mode: "0644"
            force: true

        - name: Ensure Docker APT repository is added
          ansible.builtin.apt_repository:
            repo: "{{ docker_apt_repository }}"
            filename: docker
            state: present

        - name: Ensure Docker packages are installed
          ansible.builtin.apt:
            name: "{{ docker_packages }}"
            state: present
            update_cache: true

    - name: Ensure the 'docker' group exists
      ansible.builtin.group:
        name: docker
        state: present

    - name: Ensure ansible user is added to the 'docker' group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Read the content of cmdline.txt
      ansible.builtin.slurp:
        src: /boot/firmware/cmdline.txt
      register: cmdline_content

    - name: Ensure cgroup memory options are set for Docker stats
      ansible.builtin.lineinfile:
        path: /boot/firmware/cmdline.txt
        regexp: "^(.*)$"
        line: '\1 cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1'
        backrefs: true
      when: "'cgroup_enable=memory' not in cmdline_content.content | b64decode"
      notify: Reboot for kernel changes
