---
- name: Install Docker and configure user
  become: true
  block:
    - name: Perform Docker installation
      when: "'docker-ce' not in ansible_facts.packages"
      block:
        - name: Remove conflicting Docker packages
          ansible.builtin.apt:
            name: "{{ docker_conflicting_packages }}"
            state: absent
            purge: true

        - name: Install Docker dependencies
          ansible.builtin.apt:
            name: "{{ docker_dependencies }}"
            state: present
            update_cache: true

        - name: Create Docker GPG keyring directory
          ansible.builtin.file:
            path: "{{ docker_gpg_keyring_path }}"
            state: directory
            mode: "0755"

        - name: Download Docker GPG key
          ansible.builtin.get_url:
            url: "{{ docker_gpg_key_url }}"
            dest: "{{ docker_gpg_key_path }}"
            mode: "0644"
            force: true

        - name: Add Docker APT repository
          ansible.builtin.apt_repository:
            repo: "{{ docker_apt_repository }}"
            filename: docker
            state: present

        - name: Install Docker
          ansible.builtin.apt:
            name: "{{ docker_packages }}"
            state: present
            update_cache: true

    - name: Create 'docker' group
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add ansible user to 'docker' group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Read kernel command line
      ansible.builtin.slurp:
        src: /boot/firmware/cmdline.txt
      register: cmdline_content

    - name: Enable cgroup memory for Docker stats
      ansible.builtin.lineinfile:
        path: /boot/firmware/cmdline.txt
        regexp: "^(.*)$"
        line: '\1 cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1'
        backrefs: true
      when: "'cgroup_enable=memory' not in cmdline_content.content | b64decode"
      notify: Reboot for kernel changes
