---
- name: Set up Cloudflare DDNS Updater
  vars:
    cloudflare_script: "/home/{{ ansible_user }}/cloudflare.sh"
  block:
    - name: Copy Cloudflare script
      ansible.builtin.template:
        src: "../files/cloudflare.sh.j2"
        dest: "{{ cloudflare_script }}"
        mode: "0755"
    - name: Ensure the cron job is present
      ansible.builtin.cron:
        name: "Cloudflare DDNS Updater"
        minute: "*/1"
        job: "{{ cloudflare_script }}"
      become_user: "{{ ansible_user }}"
