---
- name: Set up Cloudflare DDNS Updater
  vars:
    cloudflare_ddns_dir: "/mnt/data/cloudflare-ddns"
  block:
    - name: Create Cloudflare DDNS directory
      ansible.builtin.file:
        path: "{{ cloudflare_ddns_dir }}"
        state: directory

    - name: Copy docker-compose.yml to Cloudflare DDNS directory
      ansible.builtin.template:
        src: "../files/docker-compose.yml.j2"
        dest: "{{ cloudflare_ddns_dir }}/docker-compose.yml"

    - name: Start Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ cloudflare_ddns_dir }}"
        build: always
