name: Backup

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: Boostport/setup-cloudflare-warp@2557ba84f68223c4642f8d65d1c7371666c5af34 # v1
        with:
          organization: ${{ secrets.CLOUDFLARE_ORGANIZATION }}
          auth_client_id: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_ID }}
          auth_client_secret: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_SECRET }}
      - uses: dawidd6/action-ansible-playbook@126642a1c6ce512da255ef2b41e8ee90f0077474 # v9
        with:
          playbook: backup.yml
          requirements: requirements.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: |
            [raspberrypi]
            192.168.178.20 ansible_user=nhan ansible_python_interpreter=auto_silent
          vault_password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
